name: Push to Stoplight
on:
  push:
    branches:    
      # Push events on default branch
      - main
      # Push events to branches matching refs/heads/mona/octocat
      - 'design/'
    paths:
      - '**.json'
      - '**.yaml'
      - '**.yml'
      - '**.md'
  pull_request:
    paths:
      - '**.json'
      - '**.yaml'
      - '**.yml'
      - '**.md'
jobs:
  build:
    name: Push to Stoplight
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Push files to Stoplight
        run: |
          npx @stoplight/cli@5 push --ci-token 48d754ec-5f45-42f0-b71d-55bfc635ef70 --directory ${{ github.workspace }} --branch ${{ env.BRANCH_NAME }}